server:
  port: 0

spring:
  application:
    name: shopping-cart

  datasource:
    driverClassName: org.postgresql.Driver
    url: "jdbc:postgresql://localhost:5432/commerce?currentSchema=cart"
    username: "admin"
    password: "admin"
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties.hibernate:
      jdbc.time_zone: UTC
      format_sql: true
      temp.use_jdbc_metadata_defaults: false
    hibernate.ddl-auto: create-drop
    show-sql: false
  sql.init.mode: always

resilience4j.circuitbreaker:
  configs:
    default:
      slidingWindowSize: 50
      failureRateThreshold: 50
  instances:
    warehouse:
      slidingWindowSize: 10
      waitDurationInOpenState: 10000 # 10 секунд в миллисекундах
      permittedNumberOfCallsInHalfOpenState: 3
      slidingWindowType: COUNT_BASED
      minimumNumberOfCalls: 5
      automaticTransitionFromOpenToHalfOpenEnabled: true