server:
  port: 0

spring:
  application:
    name: warehouse

  datasource:
    driverClassName: org.postgresql.Driver
    url: "jdbc:postgresql://localhost:5432/commerce?currentSchema=warehouse"
    username: "admin"
    password: "admin"
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties.hibernate:
      jdbc.time_zone: UTC
      format_sql: true
      temp.use_jdbc_metadata_defaults: false
    hibernate.ddl-auto: create-drop
    show-sql: false
  sql.init.mode: always

logging:
  level:
    ru.yandex.practicum.commerce: TRACE
    org:
      springframework: ERROR
      springframework.cloud.netflix.eureka: INFO


