spring:
  application:
    name: aggregator

kafka:
  producer:
    uri: localhost:9092
    key-serializer: org.apache.kafka.common.serialization.StringSerializer
    value-serializer: ru.yandex.practicum.kafka.serializer.GeneralAvroSerializer

  consumer:
    uri: localhost:9092
    group-id: telemetry.aggregator
    auto-offset-reset: earliest
    enable-auto-commit: true
    key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    value-deserializer: ru.yandex.practicum.kafka.deserializer.SensorEventDeserializer

  topics:
    consumer-subscriptions:
      - telemetry.sensors.v1
    producer-topic: telemetry.snapshots.v1